version: 2
jobs:
  test:
    docker:
      - image: circleci/node
    steps:
      - checkout
      # These two tests should run in parallel. Make it so!
      - run:
         command: |
            echo $(circleci tests glob "src/test_hello.sh" "src/test_goodbye.sh")
            circleci tests glob "src/test_hello.sh" "src/test_goodbye.sh" | xargs -n 1 echo
workflows:
  version: 2
  test:
    jobs:
      - test